version: '3.7'

services:
  postgres:
    image: postgres:14.1
    ports:
      - '8090:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: todos
      POSTGRES_PASSWORD: "6zOS4G2RSnYJMy__RShiicbQSlEUMSrg"
    volumes:
      - todos_data:/var/lib/postgresql/data
  redis:
    image: redis:6.2.6
    ports:
      - '8091:6379'
    command: redis-server --requirepass "Ed8rHD3O8LeRBLXqd7_myp-KhAJXiy0r"
    environment:
      - REDIS_REPLICATION_MODE=master
  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui
volumes:
  todos_data:
